name: 'Terraform Plan and Apply'

on:
  workflow_run:
    workflows: ["Terraform Test"]
    types:
      - completed
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3        

      - name: Terraform Init
        run: terraform init

      - name: Terraform Generate Plan
        run: terraform plan -out=terraform.plan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform.plan

  terraform-apply:
    name: 'Terraform Apply Job'
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Apply the terraform plan
        run: terraform apply -auto-approve terraform.plan
